# https://help.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
registries:
  harness-npm:
    type: npm-registry
    url: https://pkg.harness.io/pkg/ct8onj8YTdaXtKaFsYCRLg/org-devtools-npm/npm/
    replaces-base: true
updates:
  - package-ecosystem: "npm"
    directory: "/"
    registries:
      - harness-npm
    cooldown:
      default-days: 14
    schedule:
      interval: "monthly"
    target-branch: "develop"
    groups:
      dev-dependencies:
        patterns:
          - "*"
        exclude-patterns:
          - "sass*"
          - "@progress/kendo-svg-icons"
      sass-dependencies:
        patterns:
          - "sass*"
      kendo-icons-dependencies:
        patterns:
          - "@progress/kendo-svg-icons"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    groups:
      all-actions:
        patterns:
          - "*"
