const esbuild = require("esbuild");
const fs = require("fs");
const p = require("path");
const { globSync } = require("glob");

// Generate baseline-data.ts with embedded test report data (if available).
// Used by the VPAT generator to provide default data for report generation.
const baselineDataPath = p.resolve("./src/vpat/baseline-data.ts");

function loadReportJSON(relPath) {
    const absPath = p.resolve(relPath);
    if (fs.existsSync(absPath)) {
        const content = fs.readFileSync(absPath, "utf-8");
        try { JSON.parse(content); return content; } catch { return null; }
    }
    return null;
}

const a11yJson = loadReportJSON("../../tests/_output/a11y-unified-report.json");
const contrastJson = loadReportJSON("../../tests/_output/contrast-report.json");

const baselineDataContent = `// @ts-nocheck — auto-generated from JSON, may have extra fields
/**
 * Baseline a11y and contrast test report data.
 *
 * This file is regenerated by packages/html/scripts/build.js at build time
 * with the latest test report data from tests/_output/.
 *
 * DO NOT EDIT MANUALLY — this file is auto-generated.
 */

import type { VpatA11yReport, VpatContrastReport } from './types';

export const baselineA11yReport: VpatA11yReport | null = ${a11yJson || 'null'};
export const baselineContrastReport: VpatContrastReport | null = ${contrastJson || 'null'};
`;

fs.writeFileSync(baselineDataPath, baselineDataContent, "utf-8");

const components = globSync("./src/**/*.tsx", { dotRelative: true, ignore: ["./src/utils/**/*.tsx", "./src/**/tests/*.tsx"] });
components.push("./src/index.ts");

const commonConfig = {
    logLevel: "error",
    entryPoints: components,
    jsx: "automatic",
    bundle: true,
    minify: true,
    sourcemap: false,
    external: [ "react", "react-dom", "@progress/kendo-svg-icons" ],
};

(async() => {
    const dist = p.resolve("./dist");
    if (!fs.existsSync(p.resolve("./dist"))) {
        fs.mkdirSync(dist);
    }
    await Promise.allSettled(
        [
            { ...commonConfig, format: "esm", target: "esnext", outdir: "./dist/esm", outExtension: { ".js": ".mjs" } },
            {
                ...commonConfig,
                format: "cjs",
                target: "node14",
                outdir: "./dist/cjs",
            },
        ].map(
            (config) =>
                new Promise((resolve) => {
                    esbuild
                        .build(config)
                        .then(resolve)
                        .catch((err) => {
                            throw new Error(err);
                        });
                })
        )
    );
})();
