name: Audit CSS

on:
  workflow_call:

concurrency:
  group: audit-css-${{ github.ref }}
  cancel-in-progress: true

jobs:

  run:
    runs-on: ubuntu-latest
    needs: []

    steps:

      - name: Checkout branch
        uses: actions/checkout@v6

      - name: Setup and Install dependencies
        uses: ./.github/actions/setup

      - name: Nx Cache
        uses: ./.github/actions/nx-cache

      - name: Run CSS compliance audit
        run: npx nx run workspace:audit:css -- all
