name: Compile themes

on:
  workflow_call:

concurrency:
  group: compile-themes-${{ github.ref }}
  cancel-in-progress: true

jobs:

  run:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout branch
        uses: actions/checkout@v6

      - name: Setup and Install dependencies
        uses: ./.github/actions/setup

      - name: Nx Cache
        uses: ./.github/actions/nx-cache
        with:
          save: 'true'
          key-suffix: compile-themes

      - name: Build themes
        run: |
          npx nx run-many -t sass

      - name: Build core docs
        run: |
          npx nx run-many -t docs

      - name: Build Meridian swatches
        run: |
          npx nx run @progress/kendo-theme-meridian:sass:dist --exclude-task-dependencies

      - name: Pack themes
        run: |
          tar -cf themes.tar \
            packages/core/dist/all.css \
            packages/core/docs \
            packages/core/dist/meta \
            packages/default/dist/all.css \
            packages/bootstrap/dist/all.css \
            packages/classic/dist/all.css \
            packages/fluent/dist/all.css \
            packages/material/dist/all.css \
            packages/meridian/dist/all.css \
            packages/meridian/dist/meridian-main.css \
            packages/meridian/dist/meridian-main-dark.css \
            packages/utils/dist/all.css

      - name: Upload themes
        uses: actions/upload-artifact@v7
        with:
          name: themes
          path: themes.tar
