name: Create screenshots

on:
  workflow_call:

concurrency:
  group: create-screenshots-${{ github.ref }}
  cancel-in-progress: true

jobs:

  run:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        theme: [default, bootstrap, material, classic, fluent, meridian]

    steps:

      - name: Cache Firefox
        id: cache-firefox
        uses: actions/cache@v5
        with:
          path: /opt/firefox
          key: firefox-latest-linux64

      - name: Download Firefox
        if: steps.cache-firefox.outputs.cache-hit != 'true'
        run: |
          sudo wget -q -O /tmp/firefox.tar.bz2 "https://download.mozilla.org/?product=firefox-latest&os=linux64&lang=en-US"
          sudo tar xJf /tmp/firefox.tar.bz2 -C /opt

      - name: Setup Firefox
        run: |
          sudo ln -sf /opt/firefox/firefox /usr/local/bin/firefox
          firefox --version

      - name: Checkout branch
        uses: actions/checkout@v6

      - name: Setup and Install dependencies
        uses: ./.github/actions/setup

      - name: Download artifacts
        uses: actions/download-artifact@v8
        with:
          path: .tmp

      - name: Unpack artifacts
        run: find .tmp -name "*.tar" -type f -exec tar -xf {} \;

      - name: Create screenshots
        run: ./build/create-screenshots.sh ${{ matrix.theme }}

      - name: Pack screenshots
        run: tar -cf screenshots-${{ matrix.theme }}.tar tests/_output/${{ matrix.theme }}

      - name: Upload screenshots
        uses: actions/upload-artifact@v7
        with:
          name: screenshots-${{ matrix.theme }}
          path: screenshots-${{ matrix.theme }}.tar
