name: CI | Docs

on:
  workflow_call:
  workflow_dispatch:

concurrency:
  group: docs-check-${{ github.ref }}
  cancel-in-progress: true

jobs:

  docs-verify:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Fetch base branch
        run: git fetch origin develop

      - name: Setup and Install dependencies
        uses: ./.github/actions/setup

      - name: Download artifacts
        uses: actions/download-artifact@v8
        with:
          path: .tmp

      - name: Unpack artifacts
        run: find .tmp -name "*.tar" -type f -exec tar -xf {} \;

      - name: Show affected projects
        run: npx nx show projects --affected --base=origin/develop

      - name: Check docs
        run: npx nx affected -t docs:check
