name: Prime cache

on:
  workflow_call:
  workflow_dispatch:

concurrency:
  group: prime-cache-${{ github.ref }}
  cancel-in-progress: true

jobs:

  run:
    name: Prime cache
    runs-on: ubuntu-latest

    steps:

      - name: Checkout branch
        uses: actions/checkout@v6

      - name: Setup and Install dependencies
        uses: ./.github/actions/setup
