name: Test HTML spec

on:
  workflow_call:

concurrency:
  group: test-html-spec-${{ github.ref }}
  cancel-in-progress: true

jobs:

  run:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout branch
        uses: actions/checkout@v6

      - name: Setup and Install dependencies
        uses: ./.github/actions/setup

      - name: Nx Cache
        uses: ./.github/actions/nx-cache
        with:
          save: 'true'
          key-suffix: html-spec

      - name: Build and check types
        run: |
          npx nx run @progress/kendo-themes-html:build
          npm run typecheck -w packages/html

      - name: Run tests
        run: |
          npx nx run @progress/kendo-themes-html:test
