name: Test HTML spec

on:
  workflow_call:

concurrency:
  group: test-html-spec-${{ github.ref }}
  cancel-in-progress: true

jobs:

  run:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout branch
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Setup node
        id: setup-node
        uses: actions/setup-node@949feb2413d6458794dcd2491c4babbbce0c15c1 # v7.1.0
        with:
          node-version: 24.x

      - name: Use cache for root node_modules
        id: cache-root-node_modules
        uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
        with:
          path: node_modules
          key: root-node_modules-${{ steps.setup-node.outputs.node-version }}-${{ hashFiles('package-lock.json') }}

      - name: Install
        if: steps.cache-root-node_modules.outputs.cache-hit != 'true'
        run: |
          npm ci --no-audit --no-fund

      - name: Build scripts
        run: |
          npm run build

      - name: Check types
        run: |
          npm run typecheck -w packages/html

      - name: Run Jest tests
        run: |
          npm run test:html
