name: Test units

on:
  workflow_call:

concurrency:
  group: test-units-${{ github.ref }}
  cancel-in-progress: true

jobs:

  run:
    runs-on: ubuntu-latest

    strategy:
        matrix:
          theme: [default, bootstrap, material, classic, fluent, meridian]

    steps:

      - name: Checkout branch
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Fetch base branch
        run: git fetch origin develop

      - name: Setup and Install dependencies
        uses: ./.github/actions/setup

      - name: Nx Cache
        uses: ./.github/actions/nx-cache

      - name: Download compiled themes
        uses: actions/download-artifact@v8
        with:
          name: themes
          path: .tmp

      - name: Unpack compiled themes
        run: tar -xf .tmp/themes.tar

      - name: Run unit tests
        run: |
          npx nx run @progress/kendo-themes-units:test -- ${{ matrix.theme }}
