name: Test units

on:
  workflow_call:

concurrency:
  group: test-units-${{ github.ref }}
  cancel-in-progress: true

jobs:

  run:
    runs-on: ubuntu-latest

    strategy:
        matrix:
          theme: [default, bootstrap, material, classic, fluent, meridian]

    steps:

      - name: Checkout branch
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Fetch base branch
        run: git fetch origin develop

      - name: Setup node
        id: setup-node
        uses: actions/setup-node@v6
        with:
          node-version: 24.x

      - name: Use cache for root node_modules
        id: cache-root-node_modules
        uses: actions/cache@v5
        with:
          path: node_modules
          key: root-node_modules-${{ steps.setup-node.outputs.node-version }}-${{ hashFiles('package-lock.json') }}

      - name: Install
        if: steps.cache-root-node_modules.outputs.cache-hit != 'true'
        run: |
          npm ci --no-audit --no-fund

      - name: Use cache for Nx
        uses: actions/cache@v5
        with:
          path: .nx/cache
          key: nx-cache-${{ github.ref }}-${{ github.sha }}
          restore-keys: |
            nx-cache-${{ github.ref }}-
            nx-cache-refs/heads/develop-
            nx-cache-

      - name: Download compiled themes
        uses: actions/download-artifact@v8
        with:
          name: themes
          path: .tmp

      - name: Unpack compiled themes
        run: tar -xf .tmp/themes.tar

      - name: Build docs
        run: |
          npx nx run @progress/kendo-theme-core:docs
          npx nx run @progress/kendo-theme-${{matrix.theme}}:docs

      - name: Run unit tests
        run: |
          npm run test:${{matrix.theme}} --prefix units
