name: Branch push

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]

    steps:
    - name: Checkout branch
      uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install
      run: |
        npm install
        npx lerna bootstrap --concurrency=1
    - name: Lint
      run: npx lerna run lint
    - name: Build
      run: |
        npx lerna run sass
        npx lerna run dart
    - name: Test
      run: |
        npm run karma-single
      env:
        CI: true
