name: CI Weekly

on:
  schedule:
    # Run at 07:20 every Monday
    - cron: '20 7 * * Mon'
  workflow_dispatch:

jobs:

  ci-weekly:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.x]

    steps:

      - name: Checkout branch
        uses: actions/checkout@v5
        with:
          ref: develop

      - name: Setup node
        id: setup-node
        uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node-version }}

      - name: Use cache for root node_modules
        id: cache-root-node_modules
        uses: actions/cache@v4
        with:
          path: node_modules
          key: root-node_modules-${{ steps.setup-node.outputs.node-version }}-${{ hashFiles('package-lock.json') }}

      - name: Install
        if: steps.cache-root-node_modules.outputs.cache-hit != 'true'
        run: |
          npm ci --no-audit --no-fund

      - name: Lint scripts
        run: |
          npm run lint:scripts

      - name: Check types
        run: |
          npm run typecheck -w packages/html

      - name: Build scripts
        run: |
          npm run build

      - name: Build test pages
        run: |
          npm run build:tests

      - name: Lint styles
        run: |
          npm run lint:styles

      - name: Build themes for dist
        run: |
          npm run sass:dist

      - name: Build docs
        run: |
          npm run docs

      - name: Check docs
        run: |
          npm run docs:check

      - name: Test integrations
        run: |
          npm run test:integrations
