name: Publish to nuget

on:
  workflow_dispatch:
  workflow_run:
    workflows:
      - "Publish to npm"
    branches:
      - master
      - develop
    types:
      - completed

env:
  NUGET_USER: kendo-bot
  NUGET_FEED: "https://nuget.pkg.github.com/telerik/index.json"

jobs:
  nuget-publish:
    if: ${{ github.event_name == 'workflow_dispatch' || github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-22.04
    environment: upload

    permissions:
      id-token: write # Required by Akeyless
      contents: read
      packages: read

    steps:
      - name: Import Secrets
        id: import-secrets
        uses: LanceMcCarthy/akeyless-action@42b5bde870ef7d135f863a035245e735bfd2ef8c # v5.7.0
        with:
          access-id: ${{ secrets.GH_AKEYLESS_ACCESS_ID }}
          static-secrets: '{ "/WebComponents/prod/tokens/GH_TOKEN_PUBLISH": "GH_TOKEN_PUBLISH" }'
          export-secrets-to-environment: false

      - name: Checkout branch
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          ref: develop

      - name: Setup node
        id: setup-node
        uses: actions/setup-node@949feb2413d6458794dcd2491c4babbbce0c15c1 # v7.1.0
        with:
          node-version: 24.x

      - name: Setup nuget
        uses: nuget/setup-nuget@fd55a6f3b34392fa83fde1454582407d8c714123 # v4.0

      - name: Check for release commit
        id: check-release
        run: |
          if [[ "${{ github.event_name }}" == "workflow_dispatch" || "$(git log -1 --pretty=%s)" == chore\(release\):* ]]; then
            echo "released=true" >> "$GITHUB_OUTPUT"
          else
            echo "released=false" >> "$GITHUB_OUTPUT"
          fi

      - name: Install
        if: steps.check-release.outputs.released == 'true'
        run: npm ci --no-audit --no-fund

      - name: Build themes for dist
        if: steps.check-release.outputs.released == 'true'
        run: |
          npm run sass:dist
          npm run docs

      - name: Pack nuget
        if: steps.check-release.outputs.released == 'true'
        run: |
          npx nx run-many -t nuget-pack --parallel=1

      - name: Push nuget
        if: steps.check-release.outputs.released == 'true'
        run: |
          nuget sources add -username ${{ env.NUGET_USER }} -password %NUGET_API_KEY% -StorePasswordInClearText -Name github -Source ${{ env.NUGET_FEED }}
          npx nx run-many -t nuget-push
        env:
          NUGET_API_KEY: ${{ steps.import-secrets.outputs.GH_TOKEN_PUBLISH }}
